<?php
/*
Plugin to retrieve the content generated by a module-tag.
Copyright (C) 2004-2021 CMS Made Simple Foundation <foundation@cmsmadesimple.org>

This file is a component of CMS Made Simple <http://www.cmsmadesimple.org>

CMS Made Simple is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of that license, or
(at your option) any later version.

CMS Made Simple is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of that license along with CMS Made Simple.
If not, see <https://www.gnu.org/licenses/>.
*/

function smarty_function_cms_module($params, $template)
{
	$out = cms_module_plugin($params, $template);
	if( !$out && isset($params['try']) ) {
		$out = '<!-- ERROR: missing module '.($params['module'] ?? '(no name)').' -->';
	}

	if( !empty($params['assign']) ) {
		$template->assign(trim($params['assign']), $out);
		return '';
	}
	return $out;
}

function smarty_cms_about_function_cms_module()
{
	echo _ld('tags', 'help_generic',
	'<p>Intial release Ted Kulp 2004</p>',
	"<li>2019 Add optional 'try' parameter</li>"
	);
}

function smarty_cms_help_function_cms_module()
{
	echo lang('tags', 'help_generic',
	'This plugin retrieves the content generated by a module-tag',
	'cms_module name="modname" ...',
	'<li>anything relevant to cms_module_plugin()</li>
<li>try: flag whether to report missing module</li>'
	);
}