<?php
/*
Plugin to retrieve the content generated by processing a named smarty GCB template.
Copyright (C) 2004-2021 CMS Made Simple Foundation <foundation@cmsmadesimple.org>
Thanks to Ted Kulp and all other contributors from the CMSMS Development Team.

This file is a component of CMS Made Simple <http://www.cmsmadesimple.org>

CMS Made Simple is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of that license, or
(at your option) any later version.

CMS Made Simple is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of that license along with CMS Made Simple.
If not, see <https://www.gnu.org/licenses/>.
*/

/**
 * @deprecated since 2.99 global content blocks are just templates since 2.0
 * @param array $params
 * @param CMSMS\internal\template_wrapper $template
 * @return mixed result of template conversion, or null
 */
function smarty_function_global_content($params, $template)
{
	$template->assign('gcb_params', $params);
	$txt = $template->fetch('cms_template:'.$params['name']);
	if( !empty($params['assign']) ) {
		$template->assign(trim($params['assign']), $txt);
		return '';
	}
	return $txt;
}

//function smarty_about_function_global_content($params, $template) {echo TODO}

//function smarty_help_function_global_content($params, $template) {echo TODO}
